package com.example.contactmanager.utils

import android.os.Build
import androidx.annotation.ChecksSdkIntAtLeast

object Constance {
    const val PREF_NAME = "my_app_prefs"
    const val IS_LOG_IN = "isLogIn"

    const val CALL_DISCONNECTED = "CALL_DISCONNECTED"
    const val ADD_TO_FAVORITE = "Add to favorite"
    const val REMOVE_TO_FAVORITE = "Remove to favorite"


    const val ACTION_SHOW_MISSED_CALLS_NOTIFICATION: String = "android.telecom.action.SHOW_MISSED_CALLS_NOTIFICATION"

    const val ACTION_UPDATE_MISSED_CALL_NOTIFICATIONS: String = "com.phonecaller.dialer.contacts.CallerId.Service.UPDATE_MISSED_CALL_NOTIFICATIONS"

    const val CALL_AUDIO_STATE: String = "CallAudioState"

    const val EXTRA_NOTIFICATION_PHONE_NUMBER: String = "android.telecom.Extra.NOTIFICATION_PHONE_NUMBER"

    const val LED_FLASH: String = "led_flash"

    const val THEME_KEY: String = "theme"

    const val UPDATE_CALL_LIST: String = "update_call_list"

    const val UPDATE_CALL_STATE: String = "update_call_state"

    const val UPDATE_CALL_TO_CONFERENCE: String = "update_call_to_conference"

    const val CONTACTS_CHANGED: String = "contacts_changed"

    const val SWIPE_ACTION_CHANGED: String = "swipe_action_changed"

    const val DIALPAD_TONE_LENGTH_MS = 150L // The length of DTMF tones in milliseconds
    const val PREFS_KEY = "Prefs"

    @ChecksSdkIntAtLeast(api = Build.VERSION_CODES.Q)
    fun isQPlus() = Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q

    @ChecksSdkIntAtLeast(api = Build.VERSION_CODES.S)
    fun isSPlus() = Build.VERSION.SDK_INT >= Build.VERSION_CODES.S




    const val APP_RUN_COUNT = "app_run_count"
    const val LAST_VERSION = "last_version"
    const val SD_TREE_URI = "tree_uri_2"
    const val PRIMARY_ANDROID_DATA_TREE_URI = "primary_android_data_tree_uri_2"
    const val OTG_ANDROID_DATA_TREE_URI = "otg_android_data_tree__uri_2"
    const val SD_ANDROID_DATA_TREE_URI = "sd_android_data_tree_uri_2"
    const val PRIMARY_ANDROID_OBB_TREE_URI = "primary_android_obb_tree_uri_2"
    const val OTG_ANDROID_OBB_TREE_URI = "otg_android_obb_tree_uri_2"
    const val SD_ANDROID_OBB_TREE_URI = "sd_android_obb_tree_uri_2"
    const val OTG_TREE_URI = "otg_tree_uri_2"
    const val SD_CARD_PATH = "sd_card_path_2"
    const val OTG_REAL_PATH = "otg_real_path_2"
    const val INTERNAL_STORAGE_PATH = "internal_storage_path"
    const val TEXT_COLOR = "text_color"
    const val BACKGROUND_COLOR = "background_color"
    const val PRIMARY_COLOR = "primary_color_2"
    const val ACCENT_COLOR = "accent_color"
    const val APP_ICON_COLOR = "app_icon_color"
    const val LAST_HANDLED_SHORTCUT_COLOR = "last_handled_shortcut_color"
    const val LAST_ICON_COLOR = "last_icon_color"
    const val CUSTOM_TEXT_COLOR = "custom_text_color"
    const val CUSTOM_BACKGROUND_COLOR = "custom_background_color"
    const val CUSTOM_PRIMARY_COLOR = "custom_primary_color"
    const val SAVE_PRIMARY_COLOR = "save_primary_color"
    const val CUSTOM_ACCENT_COLOR = "custom_accent_color"
    const val CUSTOM_APP_ICON_COLOR = "custom_app_icon_color"
    const val WIDGET_BG_COLOR = "widget_bg_color"
    const val WIDGET_TEXT_COLOR = "widget_text_color"
    const val WIDGET_LABEL_COLOR = "widget_label_color"
    const val PASSWORD_PROTECTION = "password_protection"
    const val PASSWORD_HASH = "password_hash"
    const val PROTECTION_TYPE = "protection_type"
    const val APP_PASSWORD_PROTECTION = "app_password_protection"
    const val APP_PASSWORD_HASH = "app_password_hash"
    const val APP_PROTECTION_TYPE = "app_protection_type"
    const val DELETE_PASSWORD_PROTECTION = "delete_password_protection"
    const val DELETE_PASSWORD_HASH = "delete_password_hash"
    const val DELETE_PROTECTION_TYPE = "delete_protection_type"
    const val PROTECTED_FOLDER_PATH = "protected_folder_path_"
    const val PROTECTED_FOLDER_HASH = "protected_folder_hash_"
    const val PROTECTED_FOLDER_TYPE = "protected_folder_type_"
    const val KEEP_LAST_MODIFIED = "keep_last_modified"
    const val USE_ENGLISH = "use_english"
    const val USE_ICON_TABS = "use_icon_tabs"
    const val USE_DIVIDERS = "use_dividers"
    const val USE_COLORED_CONTACTS = "colored_contacts"
    const val NEED_RESTART = "need_restart"
    const val WAS_USE_ENGLISH_TOGGLED = "was_use_english_toggled"
    const val IS_GLOBAL_THEME_ENABLED = "is_global_theme_enabled"
    const val IS_SYSTEM_THEME_ENABLED = "is_using_system_theme"
    const val IS_AUTO_THEME_ENABLED = "is_using_auto_theme"
    const val WAS_CUSTOM_THEME_SWITCH_DESCRIPTION_SHOWN = "was_custom_theme_switch_description_shown"
    const val SHOW_INFO_BUBBLE = "show_info_bubble"
    const val LAST_CONFLICT_RESOLUTION = "last_conflict_resolution"
    const val LAST_CONFLICT_APPLY_TO_ALL = "last_conflict_apply_to_all"
    const val LAST_COPY_PATH = "last_copy_path"
    const val HAD_THANK_YOU_INSTALLED = "had_thank_you_installed"
    const val SKIP_DELETE_CONFIRMATION = "skip_delete_confirmation"
    const val ENABLE_PULL_TO_REFRESH = "enable_pull_to_refresh"
    const val SCROLL_HORIZONTALLY = "scroll_horizontally"
    const val PREVENT_PHONE_FROM_SLEEPING = "prevent_phone_from_sleeping"
    const val LAST_USED_VIEW_PAGER_PAGE = "last_used_view_pager_page"
    const val USE_24_HOUR_FORMAT = "use_24_hour_format"
    const val SUNDAY_FIRST = "sunday_first"
    const val WAS_ALARM_WARNING_SHOWN = "was_alarm_warning_shown"
    const val WAS_REMINDER_WARNING_SHOWN = "was_reminder_warning_shown"
    const val USE_SAME_SNOOZE = "use_same_snooze"
    const val SNOOZE_TIME = "snooze_delay"
    const val VIBRATE_ON_BUTTON_PRESS = "vibrate_on_button_press"
    const val YOUR_ALARM_SOUNDS = "your_alarm_sounds"
    const val SILENT = "silent"
    const val OTG_PARTITION = "otg_partition_2"
    const val IS_USING_MODIFIED_APP_ICON = "is_using_modified_app_icon"
    const val INITIAL_WIDGET_HEIGHT = "initial_widget_height"
    const val WIDGET_ID_TO_MEASURE = "widget_id_to_measure"
    const val WAS_ORANGE_ICON_CHECKED = "was_orange_icon_checked"
    const val WAS_APP_ON_SD_SHOWN = "was_app_on_sd_shown"
    const val WAS_BEFORE_ASKING_SHOWN = "was_before_asking_shown"
    const val WAS_BEFORE_RATE_SHOWN = "was_before_rate_shown"
    const val WAS_INITIAL_UPGRADE_TO_PRO_SHOWN = "was_initial_upgrade_to_pro_shown"
    const val WAS_APP_ICON_CUSTOMIZATION_WARNING_SHOWN = "was_app_icon_customization_warning_shown"
    const val APP_SIDELOADING_STATUS = "app_sideloading_status"
    const val DATE_FORMAT = "date_format"
    const val WAS_OTG_HANDLED = "was_otg_handled_2"
    const val WAS_UPGRADED_FROM_FREE_SHOWN = "was_upgraded_from_free_shown"
    const val WAS_APP_RATED = "was_app_rated"
    const val WAS_SORTING_BY_NUMERIC_VALUE_ADDED = "was_sorting_by_numeric_value_added"
    const val WAS_FOLDER_LOCKING_NOTICE_SHOWN = "was_folder_locking_notice_shown"
    const val LAST_RENAME_USED = "last_rename_used"
    const val LAST_RENAME_PATTERN_USED = "last_rename_pattern_used"
    const val LAST_EXPORTED_SETTINGS_FOLDER = "last_exported_settings_folder"
    const val LAST_EXPORTED_SETTINGS_FILE = "last_exported_settings_file"
    const val LAST_BLOCKED_NUMBERS_EXPORT_PATH = "last_blocked_numbers_export_path"
    const val BLOCK_UNKNOWN_NUMBERS = "block_unknown_numbers"
    const val BLOCK_HIDDEN_NUMBERS = "block_hidden_numbers"
    const val FONT_SIZE = "font_size"
    const val WAS_MESSENGER_RECORDER_SHOWN = "was_messenger_recorder_shown"
    const val DEFAULT_TAB = "default_tab"
    const val START_NAME_WITH_SURNAME = "start_name_with_surname"
    const val FAVORITES = "favorites"
    const val SHOW_CALL_CONFIRMATION = "show_call_confirmation"
    const val COLOR_PICKER_RECENT_COLORS = "color_picker_recent_colors"
    const val SHOW_CONTACT_THUMBNAILS = "show_contact_thumbnails"
    const val SHOW_PHONE_NUMBERS = "show_phone_numbers"
    const val FORMAT_PHONE_NUMBERS = "format_phone_numbers"
    const val SHOW_ONLY_CONTACTS_WITH_NUMBERS = "show_only_contacts_with_numbers"
    const val IGNORED_CONTACT_SOURCES = "ignored_contact_sources_2"
    const val LAST_USED_CONTACT_SOURCE = "last_used_contact_source"
    const val ON_CONTACT_CLICK = "on_contact_click"
    const val SHOW_CONTACT_FIELDS = "show_contact_fields"
    const val SHOW_TABS = "show_tabs"
    const val SHOW_DIALPAD_BUTTON = "show_dialpad_button"
    const val SPEED_DIAL = "speed_dial"
    const val LAST_EXPORT_PATH = "last_export_path"
    const val WAS_LOCAL_ACCOUNT_INITIALIZED = "was_local_account_initialized"
    const val SHOW_PRIVATE_CONTACTS = "show_private_contacts"
    const val MERGE_DUPLICATE_CONTACTS = "merge_duplicate_contacts"
    const val FAVORITES_CONTACTS_ORDER = "favorites_contacts_order"
    const val FAVORITES_CUSTOM_ORDER_SELECTED = "favorites_custom_order_selected"
    const val VIEW_TYPE = "view_type"
    const val CONTACTS_GRID_COLUMN_COUNT = "contacts_grid_column_count"
    const val AUTO_BACKUP = "auto_backup"
    const val AUTO_BACKUP_FOLDER = "auto_backup_folder"
    const val AUTO_BACKUP_FILENAME = "auto_backup_filename"
    const val LAST_AUTO_BACKUP_TIME = "last_auto_backup_time"
    const val PASSWORD_RETRY_COUNT = "password_retry_count"
    const val PASSWORD_COUNTDOWN_START_MS = "password_count_down_start_ms"
    const val LAST_UNLOCK_TIMESTAMP_MS = "last_unlock_timestamp_ms"
    const val UNLOCK_TIMEOUT_DURATION_MS = "unlock_timeout_duration_ms"
    const val SHOW_CHECKMARKS_ON_SWITCHES = "show_checkmarks_on_switches"
    const val FIRST_DAY_OF_WEEK = "first_day_of_week"
    const val CUSTOM_FONT_TYPE = "custom_font_type"
    const val CUSTOM_FONT_FILE_NAME = "custom_font_file_name"
    const val LAST_ERROR = "last_error"
}